name: justedlev-msrv
services:
  configuration-server:
    container_name: ${SPRING_APPLICATION_NAME}
    image: justedlev/config-center:latest
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8888:${SERVER_PORT}'
    volumes:
      - ./config.d:${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATION}
      - ./logs:/var/log/${SPRING_APPLICATION_NAME}
