spring:
  application:
    name: '@project.name@'
  cloud:
    config:
      server:
        native:
          search-locations:
            - ./static
management:
  info:
    build:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: ${spring.application.name}
    app-group-name: justedlev-msrv
    appname: ${spring.application.name}
    hostname: localhost
  client:
    service-url:
      default-zone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/
logging:
  file:
    path: ./logs
    name: ${logging.file.path}/latest.log
  threshold:
    file: INFO
    console: INFO
  level:
    root: debug
security:
  whitelist:
    GET:
      - /webjars/**
      - /v3/api-docs/**
      - /*/v3/api-docs/**
      - /*/*/v3/api-docs/**
      - /swagger-ui.html
      - /swagger-ui/**
      - /swagger-resources
      - /swagger-resources/**
      - /configuration/ui
      - /configuration/security
      - /actuator/**
      - /*/actuator/**
      - /error
    POST:
      - /sso/logout
      - /logout
